# Generated by Django 5.2.11 on 2026-04-26 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEconomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('total_shares', models.BigIntegerField(default=1000000)),
                ('share_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('assets_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('liabilities_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('industry_multiplier', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='economics', to='products.company')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='products.company')),
            ],
            options={
                'unique_together': {('company_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_files/')),
                ('file_type', models.CharField(max_length=20)),
                ('source_department', models.CharField(max_length=100)),
                ('target_department', models.CharField(max_length=100)),
                ('linked_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='products.customdepartment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='products.company')),
                ('related_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='products.datafile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='products.company')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, default='My Company', max_length=200)),
                ('role', models.CharField(choices=[('developer', 'المطور / Super Admin'), ('owner', 'مالك/CEO'), ('manager', 'مدير إدارة'), ('engineer', 'طاقم عمل / مهندس')], db_index=True, default='engineer', max_length=50)),
                ('sector', models.CharField(choices=[('corporate', 'شركات / تجاري'), ('education', 'تعليمي / مدارس / جامعات'), ('medical', 'طبي / مستشفيات / عيادات'), ('construction', 'إنشاءات / عقارات (Villas)')], default='corporate', max_length=50)),
                ('plan', models.CharField(choices=[('free', 'مجاني (فترة تجريبية)'), ('1_month', 'شهر (8000 ج.م)'), ('3_months', 'ثلاثة أشهر (23000 ج.م)'), ('1_year', 'سنة (90000 ج.م)')], default='free', max_length=50)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary_owner', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='products.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customdepartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('google_maps_link', models.URLField(blank=True)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('forecasted_completion_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('on_hold', 'متوقف مؤقتاً')], default='active', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='products.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('danger', 'خطر'), ('warning', 'تحذير'), ('safe', 'آمن')], default='warning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.project')),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='products.project'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('class_room', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='products.company')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('cut', 'هربان')], default='present', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='products.student')),
            ],
        ),
    ]
