# Generated by Django 5.2.11 on 2026-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_materialstock_company_remove_student_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentrecord',
            name='ai_insight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
