# Generated by Django 5.2.11 on 2026-04-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_materialstock_company_remove_student_company_and_more'),
    ]

    operations = [
    ]
