# Generated by Django 5.2.11 on 2026-05-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_materialstock_company_remove_student_company_and_more'),
    ]

    operations = [
        # Tables were already removed or never existed in the production database
    ]
