# Generated by Django 5.2.11 on 2026-05-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_materialstock_company_remove_student_company_and_more'),
    ]

    operations = [
        # Tables were already removed or never existed
    ]
