# Generated by Django 5.2.11 on 2026-05-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_materialstock_company_remove_student_company_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='materialstock',
                    name='company',
                ),
                migrations.RemoveField(
                    model_name='student',
                    name='company',
                ),
                migrations.DeleteModel(
                    name='AttendanceLog',
                ),
                migrations.DeleteModel(
                    name='MaterialStock',
                ),
                migrations.DeleteModel(
                    name='Student',
                ),
            ],
            database_operations=[],
        ),
    ]
