# Generated by Django 5.2.11 on 2026-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_materialstock_company_remove_student_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdepartment',
            name='template_slug',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='grades',
            field=models.TextField(blank=True, help_text='سجل الدرجات', null=True),
        ),
    ]
