# Generated by Django 5.2.11 on 2026-05-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_customdepartment_template_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdepartment',
            name='active_modules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
