# Generated by Django 5.2.11 on 2026-05-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_customdepartment_active_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyeconomics',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
