# Generated by Django 5.2.11 on 2026-05-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_platform_admin',
            field=models.BooleanField(default=False),
        ),
    ]
