# Generated by Django 5.2.11 on 2026-05-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_profile_is_platform_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlog',
            name='status',
            field=models.CharField(choices=[('working', 'يعمل'), ('maintenance', 'في الصيانة'), ('broken', 'معطل')], default='working', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('unpaid', 'إجازة بدون راتب'), ('emergency', 'إجازة طارئة'), ('maternity', 'إجازة وضع')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='legalcontract',
            name='contract_type',
            field=models.CharField(choices=[('service', 'عقد خدمة'), ('employment', 'عقد عمل'), ('nda', 'اتفاقية سرية'), ('partnership', 'عقد شراكة'), ('supplier', 'عقد توريد'), ('lease', 'عقد إيجار')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='legalcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('expired', 'منتهي'), ('terminated', 'ملغي')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='status',
            field=models.CharField(choices=[('planned', 'مخططة'), ('active', 'نشطة'), ('paused', 'متوقفة'), ('completed', 'مكتملة')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalinventory',
            name='category',
            field=models.CharField(choices=[('medicine', 'أدوية'), ('equipment', 'أجهزة طبية'), ('supplies', 'مستلزمات')], max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'تمت الموافقة'), ('received', 'تم الاستلام'), ('cancelled', 'ملغي')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='stage',
            field=models.CharField(choices=[('lead', 'عميل محتمل'), ('qualified', 'مؤهل'), ('proposal', 'عرض سعر'), ('negotiation', 'تفاوض'), ('won', 'صفقة ناجحة'), ('lost', 'صفقة خاسرة')], default='lead', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('graduated', 'خريج'), ('transferred', 'منقول')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], default='open', max_length=20),
        ),
    ]
