# Generated by Django 5.2.11 on 2026-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_leaverequest_hr_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdepartment',
            name='custom_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customdepartment',
            name='ui_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='departmentrecord',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
